### PR TITLE
Multiple Updates

### LINKED ISSUE #14: User's mute settings aren't persisted on page refresh
If a user mutes their microphone or video and the page is refreshed, they will re-join with their camera and audio unmuted.

Since the DM can easily cause a page refresh to occur by making several changes (like enabling/disabling any module), this is quite a privacy risk for end users.

I see two possible solutions:
1. Persist the mute settings as a user setting so it is read and used when reconnecting.
2. Always start users with camera & microphone muted.

I think the first option is likely better since it gives the user the choice and the second option may cause confusion. Might not be bad to make the second solution a setting that could be enabled as a module setting (default off), though.

### PR DESCRIPTION
**Pull request by bekriebel**
This includes multiple changes. I have been running most of these on my instance for a few sessions. I'll be running again on June 6th if you want me to give it one more round of testing. Also, if you'd like me to break these up into different PRs or remove any specific changes, let me know.

* Remove an uneeded call to setVideoStream (further reduces unneeded update calls)
* Stop using the beta jitsi meet servers when using default servers
* Update lib-jitsi-meet to current version
* Disable video stream on startup if the user is hidden (Fixes #14)

### CODE REVIEW

**Comment by luvolondon** [comment]
Hi, I just reversed "Use the non-beta jitsi meet server for default". It broke access when using the public service. Need to get off to work, will look into it later. I´m sure there is a way to remove the beta urls, but I´m not sure how atm.

**Comment by bekriebel** [comment]
> Hi, I just reversed "Use the non-beta jitsi meet server for default". It broke access when using the public service. Need to get off to work, will look into it later. I´m sure there is a way to remove the beta urls, but I´m not sure how atm.

Hrmm... Do you have an error from it? I've tested that quite a bit and also ran an entire session with those changes in place.

**Comment by luvolondon** [comment]
Did you run it with the default server or your own custom server? The error happens with the default server, since that is where the settings come into play. It was reported by two users on Discord and I could reproduce it with my install. 
This was one the reports: https://discordapp.com/channels/170995199584108546/513918036919713802/719675180628312125

**Comment by bekriebel** [comment]
I had been testing it with the defaults. However, I may have also still been running off of my branch version. I'll reset to the code the was in place on the main branch and try again soon.

**Comment by luvolondon** [comment]
I had tried to use the non-beta hosts before and had no luck. Others have the same problem: 
https://community.jitsi.org/t/connection-failed-using-lib-jitsi-meet/20774/2
I´ve no idea why you cannot connect to the public non-beta servers.

**Comment by bekriebel** [comment]
Weird. I just confirmed I'm on the v0.2.25 version and it's connecting with the default servers:

```
JitsiRTC :  JitsiMeetJS init with options  
{hosts: {…}, bosh: "//meet.jit.si/http-bind", clientNode: "http://meet.jit.si"}
bosh: "//meet.jit.si/http-bind"
clientNode: "http://meet.jit.si"
hosts: {domain: "meet.jit.si", muc: "conference.meet.jit.si"}
__proto__: Object
```

```
JitsiRTC :  Connection created with options  
{hosts: {…}, bosh: "//meet.jit.si/http-bind", clientNode: "http://meet.jit.si"}
bosh: "//meet.jit.si/http-bind"
clientNode: "http://meet.jit.si"
hosts: {domain: "meet.jit.si", muc: "conference.meet.jit.si"}
__proto__: Object
```

**Comment by bekriebel** [comment]
Yeah, a quick scan of the forums makes it look like there are intermittent issues with the "stable" servers. I guess if the beta ones tend to work more often, we may as well stick with those.

**Pull request merged**
