### PR TITLE
Spanish updated and fix for en.json

### PR DESCRIPTION
**Pull request by lozalojo**
LiveKit Server Password -> Jitsi Server Password

### CODE REVIEW

**Comment by bekriebel** [comment]
This was manually rebased and merged in to fix some whitespace differences and remove the multiple merge commits. When you get the chance, can you check out a clean copy of the `main` branch so the merge commits aren't included in your next push? Thank you!

**Comment by lozalojo** [comment]
Sorry, I have to learn more about git, honestly, my knowledge is very limited, thanks for fixing the PR

**Comment by bekriebel** [comment]
All good! I don't mind fixing them up, and I really appreciate the contribution.

If you'd like some tips, what you can do before starting to make changes is `git fetch origin` then `git reset --hard origin/main`. (Assuming `origin` is the name of the git remote that is set up for the original repo. If that's different, just change `origin` to whatever it is named on your end). This will pull the latest changes from the original repo and then reset your local version to be what is currently in the `main` branch there.

If you've already done some work and want to fetch the latest updates and put your work on top of it, you would instead use `git rebase`. I highly recommend learning about rebase, it's a super powerful git command.

What I did in this case was checked out your changes, then did `git fetch origin` then `git rebase -i origin/main`. That put your changes in on top of the latest code and then I pushed it up to github.

**Comment by lozalojo** [comment]
Thank you, looks like I have to start using the command line, since currently I use just guis.

**Comment by bekriebel** [comment]
I'm sure there are ways to do similar things with the GUI. I'm just in the habit of the command line :-)

**Pull request closed without merging**
